In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
voc_size = 1000

In [21]:
one_hot_repr = [one_hot(words,voc_size)for words in sent]

In [22]:
one_hot_repr

[[949, 325, 200, 567],
 [949, 325, 200, 500],
 [949, 985, 200, 53],
 [427, 886, 881, 304, 299],
 [427, 886, 881, 304, 353],
 [34, 949, 786, 200, 363],
 [739, 357, 247, 304]]

In [23]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
sent_length =8 
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 949 325 200 567]
 [  0   0   0   0 949 325 200 500]
 [  0   0   0   0 949 985 200  53]
 [  0   0   0 427 886 881 304 299]
 [  0   0   0 427 886 881 304 353]
 [  0   0   0  34 949 786 200 363]
 [  0   0   0   0 739 357 247 304]]


In [26]:
dim=10

In [27]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\jaipr\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step


array([[[ 0.04638029,  0.04725946,  0.04843288,  0.04733069,
         -0.04026391, -0.01084854, -0.03878529, -0.00035832,
          0.01189755,  0.00386431],
        [ 0.04638029,  0.04725946,  0.04843288,  0.04733069,
         -0.04026391, -0.01084854, -0.03878529, -0.00035832,
          0.01189755,  0.00386431],
        [ 0.04638029,  0.04725946,  0.04843288,  0.04733069,
         -0.04026391, -0.01084854, -0.03878529, -0.00035832,
          0.01189755,  0.00386431],
        [ 0.04638029,  0.04725946,  0.04843288,  0.04733069,
         -0.04026391, -0.01084854, -0.03878529, -0.00035832,
          0.01189755,  0.00386431],
        [-0.01882606,  0.01058706,  0.00351533,  0.02420619,
         -0.01950327, -0.02142453, -0.03399694,  0.03524405,
          0.00892824, -0.03394586],
        [ 0.04168342, -0.01290116, -0.04713699,  0.01800864,
          0.04373673,  0.02667022,  0.00797803,  0.04035871,
          0.03961309,  0.03700965],
        [ 0.04908333, -0.01163099, -0.03505485, -0.0

In [30]:
embedded_docs[0]

array([  0,   0,   0,   0, 949, 325, 200, 567])

In [31]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [32]:
print(embedded_docs[0].shape)


(8,)


In [33]:
import numpy as np

# Add batch dimension to match expected input shape
input_data = np.expand_dims(embedded_docs[0], axis=0)  # Shape becomes (1, 100)
predictions = model.predict(input_data)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[[[ 0.04638029  0.04725946  0.04843288  0.04733069 -0.04026391
   -0.01084854 -0.03878529 -0.00035832  0.01189755  0.00386431]
  [ 0.04638029  0.04725946  0.04843288  0.04733069 -0.04026391
   -0.01084854 -0.03878529 -0.00035832  0.01189755  0.00386431]
  [ 0.04638029  0.04725946  0.04843288  0.04733069 -0.04026391
   -0.01084854 -0.03878529 -0.00035832  0.01189755  0.00386431]
  [ 0.04638029  0.04725946  0.04843288  0.04733069 -0.04026391
   -0.01084854 -0.03878529 -0.00035832  0.01189755  0.00386431]
  [-0.01882606  0.01058706  0.00351533  0.02420619 -0.01950327
   -0.02142453 -0.03399694  0.03524405  0.00892824 -0.03394586]
  [ 0.04168342 -0.01290116 -0.04713699  0.01800864  0.04373673
    0.02667022  0.00797803  0.04035871  0.03961309  0.03700965]
  [ 0.04908333 -0.01163099 -0.03505485 -0.03491944  0.00951016
    0.04829326 -0.04245346  0.04458446  0.02390191  0.02844472]
  [-0.03598347 -0.03308713  0.0380422  -0.02461133  0.03898733
    0.0295